FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN echo "==> Upgrading apk and installing system utilities ...." \
 && apt -y update \
 && sudo apt install -y git-all

RUN echo "==> Installing Python3 and pip ...." \  
 && apt-get install python3 -y \
 && apt install python3-pip -y

RUN pip install pygame
RUN pip install numpy

RUN echo "==> Adding Blender Part Two Git Clone..." \
  && mkdir ~/blender-git \
  && cd ~/blender-git \
  && git clone https://github/automateyournetwork/pdntspa.git

CMD ["/pdntspa/PDNTSPA/python PDNTSPA.py"]