FROM ubuntu:latest

RUN echo "==> Upgrading apk and installing system utilities ...." \
 && apt -y update \
 && apt-get -y install sudo 

RUN echo "==> Install Git ...." \ 
 && sudo DEBIAN_FRONTEND=noninteractive apt install -y git-all

RUN echo "==> Installing Python3 and pip ...." \  
 && apt-get install python3 -y \
 && apt install python3-pip -y

RUN echo "==> Installing pyGame ...." \  
  && pip install pygame

RUN echo "==> Installing numply ...." \  
  && pip install numpy

RUN echo "==> Installing numply ...." \
  && sudo apt-get -y install python3-tk

RUN echo "==> Git Clone..." \
  && git clone https://github.com/automateyournetwork/pdntspa.git

CMD  [ "python3", "./pdntspa/PDNTSPA/PDNTSPA.py" ]